### ISSUE TITLE
enhacement: add member role

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#107]
Scenario:
Actually the member is being created by an admin or super-admin user but it doesn't have a role so the member user can't be logged

GIVEN:
i logged as an ADMIN USER

WHEN:
I go to ORGANIZATION list, and enter some ORGANIZATION,

THEN:
go to create a new member, the memeber is being created by selecting an user but the role doesn't change

evidence:
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/c7aea6ba-b516-43e8-9394-f2f2f46818db)

**Comment by davidurosa** [comment]
The "member" role was added to the system roles, which has allowed users with this role to log in successfully.
