### ISSUE TITLE
bug: the landing page on the server is not loading the internal pages

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#112]
Scenario:
When entering the landing page from the server and trying to access the internal pages, a 500 error appears

GIVEN:
The landing is accessed on the server

WHEN:
Click on about push hands in the top menu

THEN:
Regardless of the option selected, be it styles, organizations or teachers, the 500 error still appears.

evidence:

**on server**:
![Screenshot_1](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/3ab84fc1-b235-4314-a7e4-0a4cb2dfad53)

**on local**:
![Screenshot_2](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/bf80f440-07ae-4c8e-b872-4d722f220152)

**Comment by davidurosa** [comment]
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/63a23fe3-ad23-4d79-967c-7148444c71e6)

done
