### ISSUE TITLE
bug: the teachers associated with the events are not being shown on the landing page

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#113]
Scenario:
The information about the teachers is not being loaded on the event details page on the landing page.

GIVEN:
enter the landing

WHEN:
select any category and click on view all events, in the list of events

THEN:
When you click on read more, it loads the event details page, when you scroll down at the bottom there is the teachers section but they are not showing

evidence:

**landing**
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/700ba061-5454-488c-b0d6-bf6a43803227)

**backoffice**
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/b0136e28-32b1-48df-8cf8-46c3fc2b7089)

**Comment by davidurosa** [comment]
done
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/974b03af-08d4-4b11-b7cb-c6a454cbea33)
