### ISSUE TITLE
ux: make events in the carousel clickable to see event details quickly

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#114]
Scenario:
When you enter the landing page, a carousel of events is shown, but to access them you must select to see all the elements in the category, then within the list, search for the event and then if you click, you can see the event.

GIVEN:
enter the landing

WHEN:
select any category and click on view all events, in the list of events

THEN:
Clicking read more loads the event details page.

solution:
For user convenience it is necessary to make the carousel events clickable

**Comment by davidurosa** [comment]
List has already added a button that redirects to the event
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/f629bc42-35d7-4215-a078-37b29fc378e5)
