### ISSUE TITLE
enhacement: create a list of instructors who are not part of the staff

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#115]
Scenario:
Currently, to add the speaker to an event, any instructor in the system is taken directly.

GIVEN:
Currently, to add the speaker to an event, any instructor in the system is taken directly.

WHEN:
the speaker is saved, it must be considered that an invitation process will be carried out in the future

THEN:
It is important that the user keep in mind which instructors belong to the organization or which ones should send an invitation.

solution:
Create a new get method with all instructors who do not belong to the organization's staff

**Comment by davidurosa** [comment]
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/0d878f93-0079-4b32-9b1e-651c3a3c7693)

Done, the instructor list has now been created to view instructors who are not related to the organization.
