### ISSUE TITLE
bug: delete all factory seeders

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#118]
Scenario:
currently there are seeders for all tables in the database

GIVEN:
with the current system

WHEN:
when migrations take place

THEN:
database tables are loaded with false data for testing

evidence:
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/b60cf96f-047e-44cb-8871-3877576089c6)

solution:
The client asked us to leave the database blank and only leave the cluster data

**Comment by kunaisoft** [comment]
@all

guys, I think this is not necesarilly a bug. I remember that Mariana talked about this requirement from Severin regarding populating just Clusters data. 
But please keep in mind that we can populate just one table by using a specific flag with the Laravel command.

fyi: @marianamartineza @davidurosa

**Comment by marianamartineza** [comment]
@kunaisoft 

Got it, how can we name It? If not as bug? As task? Or It is better that i delete this issue?

**Comment by davidurosa** [comment]
done
