### ISSUE TITLE
enhacement: create a list of instructors who are not assigned to the event

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#125]
Scenario:
create a list of instructors who are not assigned to the event

GIVEN:
Currently, to add the speaker to an event, all instructors are taken globally.

WHEN:
When the speaker is created, the instructor must not have already been assigned to the event.

THEN:
If the user selects an instructor that has already been assigned, the duplicate key error is triggered.

solution:
create new get method for the instructors who are not assigned to the event

**Comment by davidurosa** [comment]
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/8765f973-8280-45f0-bfc8-59f1858cf052)

done, the instructor list has now been created to view instructors who are not related to the event.
