### ISSUE TITLE
ux: change logo in home page

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#138]
Scenario:
change logo in home

GIVEN:
go to home in landing page

WHEN:
the client send us a new design, we need to adapt the actual landing 

THEN:
the logo in the header need to be changed

evidence:

**landing**
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/3c74b700-3b9f-4465-815c-5b4813484218)

**design**
![logo design](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/3ef28a98-ff55-4acb-9978-68191b47e88a)

**Comment by davidurosa** [comment]
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/5b29ad72-d20d-46e8-985e-fcfc9eda2c0f)
done
