### ISSUE TITLE
ux: change small font size in home landing page

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#139]
Scenario:
change small font size in home landing page

GIVEN:
go to home in landing page

WHEN:
the client send us a new design, we need to adapt the actual landing 

THEN:
the small font size need to be bigger

evidence:

**landing**
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/7ded5db3-d367-419e-9fc5-31a32b6c9e4d)

**design**
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/66cbcdb9-5d6c-4e34-8eec-fe905956ef22)

**Comment by davidurosa** [comment]
done
