### ISSUE TITLE
ux: need to change font for titles landing

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#140]
Scenario:
change font for titles in landing

GIVEN:
go to home in landing page

WHEN:
the client send us a new design, we need to adapt the actual landing

THEN:
when scroll down the font for the titles need to be changed

evidence:

**landing**
![Screenshot_26](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/3455948b-5bce-44ab-afbf-f653c267a1be)

**design**
![Screenshot_8](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/19b991aa-9a25-4597-bacf-fe2428ddfa21)

**Comment by davidurosa** [comment]
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/c95c6b8e-07c8-4ea2-a918-a3a306f9180d)
done
