### ISSUE TITLE
enhacement: add online courses

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#142]
Scenario:
The online courses must be added when the clusters are created and in the landing page

GIVEN:
Currently, the push hands platform works with general events that do not specify whether they are virtual or not.

WHEN:
The event is created, only a general category is specified.

THEN:
online courses must be added

evidence:

**design**
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/7c860868-3e72-471c-adfb-2e48cdb22efb)

**Comment by davidurosa** [comment]
done : 
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/3c3e5e2c-da67-4854-b152-6062fc50458b)
