### ISSUE TITLE
enhacement: add new info to teacher page

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#145]
Scenario:
Online activities must be added to the teacher's profile, space must also be added to contain the teacher's videos and images.

GIVEN:
Currently, the teacher's page with basic information has been implemented on the Push Hands platform.

WHEN:
You click on about push hands, and on teachers, you can choose to see the profile of a specific teacher

THEN:
and currently we have the description and some base data. Update the data to match the design

evidence

**design:**
![Screenshot_16](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/8f3f9a62-bfc4-4d7d-ab12-3d80280e97ae)

![Screenshot_18](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/6a4edcf8-b281-498b-9abf-05b86c98bb4b)

![Screenshot_19](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/b9a07b7c-cca8-4b8e-a4f5-a99a161a8e50)

**Comment by davidurosa** [comment]
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/b2813b19-56f6-4254-b947-6f54e9855429)
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/5d2ba9bc-3812-4ecf-aa50-2a7a6c422d98)
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/6c6b1fcb-1739-43ed-a167-3d4f78f21c7d)
 done
