### ISSUE TITLE
enhacement: add video landing page

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#150]
Scenario:
the video page must be implemented

GIVEN:
on the landing

WHEN:
about push hands is clicked

THEN:
and in the drop-down list videos is selected, it does not load anything

evidence:

**design**
![Screenshot_34](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/6dbb35fa-8f19-4846-b5d8-5fa35a6f9605)

**Comment by davidurosa** [comment]
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/ab964587-3e6c-48b6-b536-3a18b9431d1b)
done
