### ISSUE TITLE
enhacement: add new info in style detail page

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#153]
Scenario:
videos module must be added to the style details page

GIVEN:
Currently, the style details page with basic information has been implemented on the Push Hands platform.

WHEN:
You click on about push hands, and on styles, you can choose to see a specific style

THEN:
and currently we have the description and some base data. Update the data to match the design

evidence

design
![Screenshot_37](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/2d3b4913-a478-4521-8998-a69cd8c34fed)

![Screenshot_38](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/f252203f-0f3e-4a00-b39c-cd9678071b56)

**Comment by davidurosa** [comment]
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/f02ed1ac-8372-49ce-abf5-83afc2811ddb)
ready, the stylo page has been updated
