### ISSUE TITLE
enhacement: add iso_code in location table 

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#156]
Scenario:

add iso_code in locations table

GIVEN:

Currently locations info contains address, country, state, locality, postal code, description, latitude and coordinates

WHEN:

A new location is created although only the address, country, state and locality are required in the backoffice

THEN:
add iso_code in locations table

**Comment by davidurosa** [comment]
Ready, the iso code of the country has been added, in the location, to be able to obtain the flags
