### ISSUE TITLE
ux: change font type for archive title

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#186]
Scenario:
It is necessary to change the font in the title of the archived events

GIVEN:
on the landing

WHEN:
the user enters events or any category of events

THEN:
The title of the list of archived events has the old font, change it to the new one

evidence:
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/62890266-e5ec-44ac-b861-5149f1d44461)

**Comment by davidurosa** [comment]
done
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/caa976da-52fc-4897-8705-653385443549)
