### ISSUE TITLE
bug: updateEvent link all fields

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#68]
Scenario:

the foreign key fields of the event form are not being updated

GIVEN:

I logged as an admin USER

WHEN:

I go into ORGANIZER, then enter the EVENT LIST, select one EVENT and click in edit icon

THEN:
the fields of the EVENT EDIT FORM are loaded by showEvent and when they are updated (all fields were changed) and the update button is clicked, foreign key fields are not being updated

EVIDENCE:

**before updated**

![Screenshot_18](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/d37c2d24-7af3-4109-95b8-2e8397da32c8)

![Screenshot_19](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/6d93e730-8c46-4d83-86be-af572f63c228)

**after updated**

![Screenshot_20](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/f0605a9f-617e-47fa-85d6-3fc8cc23c2af)

![Screenshot_21](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/7e2d0287-4e19-47f5-95a0-4583beb356ee)

![Screenshot_22](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/5efe9dd0-b9ab-42ab-83c5-0fd0ec4fcb55)

SOLUTION:
Need to link all fields of event to be updated. Including location, category, level, timezone and email.

**Comment by davidurosa** [comment]
resolved
