### ISSUE TITLE
enhacement: Add report endpoint for super admin user

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#83]
Scenario:

Need to create a endpoint with info for organizers report in super admin user 

GIVEN:

I logged as an  SUPER ADMIN user

WHEN:
the dashboard load

THEN:
the info is static

Solution:
Create new endpoint for the report including multiple data requested by Client

![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/16a04404-48cf-4363-8d16-d46481d192d9)

**Comment by davidurosa** [comment]
done 
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/b8e9cfd8-c808-4f77-ad35-27a06e0161f6)
