### ISSUE TITLE
enhacement: Add report endpoint for admin user

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#84]
Scenario:

Need to create a endpoint with info for organizers report in super admin user

GIVEN:

I logged as an ADMIN user

WHEN:
the dashboard load

THEN:
the info is static

Solution:
Create new endpoint for the report including multiple data requested by Client

![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/0fd21e83-85b9-4797-a931-d78d4c441313)

**Comment by davidurosa** [comment]
done
