### ISSUE TITLE
bug: edit member as admin user

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#89]
Scenario:
edit member

GIVEN:
I logged as admin user

WHEN:
The user goes to a specific ORGANIZATION, go to MEMBER List

THEN:
The user selects a member to delete and clicks on the pencil icon, the form load existing data, but when clicking on the update button, the error user does not have the rigth roles is showing.

![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/49d2a81c-7446-41a6-918d-c233cc208dd9)

**Comment by davidurosa** [comment]
done
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/92e98921-12e4-4250-8be8-280268de8e98)
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/d32735a8-1284-4f4b-9815-16ad5e54ee8b)
