### ISSUE TITLE
bug: description is not optional when editing a location

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#90]
Scenario:
Now all form fields in edit Location form are needed including postal_code and description

GIVEN:

I logged as an admin USER

WHEN:

I go into LOCATION List, then select one location to edit by clicking on pencil icon

THEN:
All the field loads and description is empty click on update button and it's failing

evidence:
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/31f594d1-d03f-4b5a-a430-7f90a342ded0)

**Comment by davidurosa** [comment]
done
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/bcaed0a2-c0c1-4139-92a4-483ca25dfe6f)
