### ISSUE TITLE
enhacement: global instructor profile

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#91]
Scenario:

In a event created by an admin, its necessary to add a speaker with a global instructor

GIVEN:
i logged as an ADMIN USER

WHEN:
I go to ORGANIZATION list, and enter some ORGANIZATION, 

THEN:
go to event List, select an event, and click to add speaker actually the speaker is generated of the instructor inside each organizer 

evidence:
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Frontend_Backoffice/assets/39972760/aa74fd57-8e1f-47f8-80bb-49aa87d832bb)

Solution:
The user select a email of one of the globals instructors to create the speaker, if not exist then create a instructor by selecting a user. 

If the user doesn't exist then, the user need to be created when creating the instructor

**Comment by davidurosa** [comment]
done
