### ISSUE TITLE
enhacement: members need to be global for por users

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#93]
Scenario:

Actually new members are created inside of every organization

GIVEN:
i logged as an ADMIN USER

WHEN:
I go to ORGANIZATION list, and enter some ORGANIZATION,go to MEMBER List, click in Add Member

THEN:
the user need to upload the info to create a new member every time.

evidence:
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Frontend_Backoffice/assets/39972760/6de97ded-053c-47e0-89eb-84db1b1437dc)

Solution:

Members must be related to users, so that they can be referred within the organization without having to create a new profile each time.

Thus the member only needs to be referenced so that he can manage and work within one or more organizers

**Comment by davidurosa** [comment]
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/8c8dabc3-e519-4f40-ad77-99bf4e106daa)
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/7fd3dd0c-f03b-4245-b493-82e6cddb2aa0)

done
