### ISSUE TITLE
enhacement: make the all the events fields optionals when the event is in draft mode

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#94]
Scenario:

User can leave some blank information when the EVENT is in draft mode.

GIVEN:

I logged in as an ADMIN user.

WHEN:

I go to the create new EVENT form.

THEN:

Some of the fields are showing me errors for not being filled still when checked the draft mode.

Solution:

The fields can be blank when the user wants to create the new event in the DRAFT mode, but not when the EVENT will be pusblished.

evidence:

![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/39972760/6277a6d7-d6c7-48c8-b1df-2b60bad2a1b6)

**Comment by davidurosa** [comment]
done
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/ce0ccfde-9214-415a-be4f-ccb08e96717f)
